export const resources = {
    en:{
        translation:{
            messages: {
                eventDeleted: "Event successfully deleted",
                eventDeleteError: "Error deleting event",
                employeeCreatedSuccess: "Employee added successfully",
                employeeCreatedError: "Error creating employee",
                serverError: "Server error",
                employeeUpdatedSuccess: "Employee updated successfully",
                employeeUpdatedError: "Error updating employee",
                employeeDeletedSuccess: "Employee deleted successfully",
                employeeDeletedError: "Error deleting employee",
                projectUpdatedSuccess: "Project updated successfully",
                projectUpdatedError: "Error updating project",
                projectCreatedSuccess: "Project added successfully",
                projectCreatedError: "Error creating project",
                projectDeletedSuccess: "Project deleted successfully",
                projectDeletedError: "Error deleting project",
                fileIdNotFound: "File ID not found",
                fileDeletedSuccess: "File deleted successfully",
                eventCreatedSuccess: "Event was added successfully",
                eventCreatedError: "Error adding event",
                eventAddedSuccess: "Event added successfully",
                eventAddError: "Error adding event",
                eventUpdatedSuccess: "Event updated successfully",
                eventUpdateError: "Error updating event",
                userAddedSuccess: "User added successfully",
                userRegisterError: "Error registering user",
                userUpdatedSuccess: "User updated successfully",
                userUpdateError: "Error updating user",
                userDeletedSuccess: "User deleted successfully",
                userDeleteError: "Error deleting user",
                documentAddedSuccess: "Document added successfully",
                documentCreateError: "Error creating document",
                documentUpdatedSuccess: "Document updated successfully",
                documentUpdateError: "Error updating document",
                documentDeletedSuccess: "Document deleted successfully",
                documentDeleteError: "Error while deleting the document",
                expertAddedSuccess: "Expert added successfully",
                expertCreateError: "Error creating expert",
                expertUpdatedSuccess: "Expert updated successfully",
                expertUpdateError: "Error updating expert",
                expertDeletedSuccess: "Expert deleted successfully",
                expertDeleteError: "Error deleting expert",
                employeeAddedSuccess: "Employee added successfully",
                employeeCreateError: "Error creating employee",
                employeeUpdateError: "Error updating employee",
                employeeDeleteError: "Error deleting employee",
                projectAddedSuccess: "Project added successfully",
                projectCreateError: "Error creating project",
                projectUpdateError: "Error updating project",
                projectDeleteError: "Error deleting project",
                organizationAddedSuccess: "Organization added successfully",
                organizationCreateError: "Error creating organization",
                organizationUpdatedSuccess: "Organization updated successfully",
                organizationUpdateError: "Error updating organization",
                organizationDeletedSuccess: "Organization deleted successfully",
                organizationDeleteError: "Error deleting organization",
                contractAddedSuccess: "Contract added successfully",
                contractCreateError: "Error creating contract",
                contractUpdatedSuccess: "Contract updated successfully",
                contractUpdateError: "Error updating contract",
                contractDeletedSuccess: "Contract deleted successfully",
                contractDeleteError: "Error deleting contract",
                loginSuccess: "Login successful",
                reportAddedSuccess: "Report added successfully",
                reportCreateError: "Error creating report",
                reportUpdatedSuccess: "Report updated successfully",
                reportUpdateError: "Error updating report",
                reportDeletedSuccess: "Report deleted successfully",
                reportDeleteError: "Error deleting report",
                translatorAddedSuccess: "Translator added successfully",
                translatorCreateError: "Error creating translator",
                translatorUpdatedSuccess: "Translator updated successfully",
                translatorUpdateError: "Error updating translator",
                translatorDeletedSuccess: "Translator deleted successfully",
                translatorDeleteError: "Error deleting translator"
            },
            navigation: {
                main: 'Home',
                cooperation: 'Cooperation',
                countries: 'Countries',
                internationalOrganizations: 'International organizations',
                internationalNonGovernmentalOrganizations: 'International Non-Governmental Organizations',
                internationalDocuments: 'International Documents',
                internationalTreaties: 'International Agreements',
                experts: 'Experts',
                translators: 'Translators',
                eventStatistics: 'Statistics',
                events: 'Events',
                visits: 'Visits',
                reports: 'Reports',
                administrations: 'Administration',
                employees: 'Employees'
            },
            titles: {
                main: 'Home',
                administration: 'Administration',
                cooperation: 'Cooperation',
                countries: 'Countries',
                eventStatistics: 'Event Statistics	',
                experts: 'Experts',
                internationalDocuments: 'International Documents',
                internationalNonGovernmentalOrganizations: 'International Non-Governmental Organizations',
                internationalOrganizations: 'International Organizations',
                internationalsTreaties: 'International Agreements',
                reports: 'Reports',
                statistics: 'Statistics',
                statisticsOfCountryVisits: 'Country Visit Statistics',
                translators: 'Translators',
                visitsEmployees: 'Employee Visit Statistics',
                areYouSure: 'Are you sure you want to delete',
                administrator: 'Administrator',
                overallStatistics: 'Overall statistics',
                totalMeetings: 'Total meetings',
                Agency: 'Agency',
                otherOrganizer: 'Other organizer',
                expertLevel: 'Expert-level',
                organizations: 'Organizations',
                countryOrOrganization: 'Country / Organization',
                conferenceFormat: 'Conference format',
                roles: {
                    director: "Director",
                    deputy: "Deputy",
                    expert: "Expert",
                    organizer: 'Organizer'
                }
            },
            buttons: {
                back: 'Back',
                today: 'Today   ',
                forward: 'Forward',
                month: 'Month',
                week:'Week',
                day: 'Day',
                excelDownload: 'Download Excel',
                worldDownload: 'Download Word',
                print: 'Print',
                create: 'Create',
                edit: 'Edit',
                delete: 'Delete',
                retrieve: 'View',
                add: 'Add',
                actions: 'Actions',
                cancel: 'Cancel',
                login: 'Login',
                logout: 'Logout',
                addAnotherFile: 'Add another file',
                addAnotherDate: 'Add another date',
                addAnotherCV: 'Add another CV',
                addAnotherCertificate:'Upload certificate',
                addAnotherDocument: 'Add another document',
                otherCountry: 'Other country',
                otherGovernmentBody: '	Other government body',
                addLang: 'Add language',
                selectYear: 'Select year',
                addReport: 'Add report',
                download: 'Download',
                active: 'Active',
                inactive: 'Inactive',
                sort: {
                    sortBy: 'Sort by',
                    byName: 'By name',
                    byVisit: 'By visit',
                    byMeeting: 'By meeting	',
                    all: 'All',
                    agency: 'Agency',
                    otherOrganizer: 'Other organizer',	
                }

            },
            events:{
                conference: 'Conference / Forum',
                birthday: 'Birthdays',
                delegations: 'Reception of Delegations',
                diplomatic: 'Diplomatic Receptions',
                foreign: 'Foreign Visits',
                meeting: 'Meeting / Discussion',
                personal: 'Personal Matters',
                seminar: 'Seminar / Training',
                significant: 'Significant Events',
                other: 'Other',
                online: 'Online',
                offline: 'Offline',
                letterToMFA: 'Letter to MFA',
                MFAResponse	: 'MFA Response',
                approvalFromMFA: 'Approval from MFA' ,
                letterToSSS: 'Letter to SSS',
                SSSResponse: 'SSS Response',
                approvalFromSSS: 'Approval from SSS',
                letterToAdministration: 'Letter to Administration',
                administrationResponse: 'Administration Response',
                approvalFromAdministration: 'Approval from Administration',
                foreignVisits: 'Foreign visits',
                receptionOfDelegations: 'Reception of delegations',
                diplomaticReceptions: 'Diplomatic receptions',
                hybrid: "Hybrid",
                membersQuantity: 'Members quantity'
            },
            inputs: {
                selectEvent: 'Select event',
                enterOrganizer: 'Enter organizer',
                selectFormat: 'Select format',
                numberOfParticipants: 'Number of participants',
                selectPartner: 'Select partner',
                selectDonor: 'Select donor',
                number: 'Number',
                selectDate: 'Select date',
                title: 'Title',
                uploadFile: 'Upload file',
                placeOfSigning: 'Place of signing',
                enterTitle: 'Enter title',
                enterFullName: 'Enter full name',
                additionalInformation: 'Additional information',
                uploadCV: 'Upload CV',
                uploadCertificate: 'Add another certificate',
                uploadScannedDocument: 'Upload scanned document',
                governmentBody: 'Government body',
                nameOfGovernmentBody: 'Name of government body',
                administrationsPermission: 'Administration’s permission',
                contractTitle: 'Contract title',
                levelOfSigning: 'Level of signing',
                mainAreas: 'Main areas ',
                invitingOrganization: 'Inviting organization',
                selectLanguage: 'Select a language',
                points: 'Points',
                responsible: 'Responsible',
                name: 'Name',
                role: 'Role',
                status: 'Status',
                lastLogin: 'Last login',
                lastName: 'Last Name',
                phone: 'Phone Number',
                email: 'Email',
                password: 'Password',
                nameOfTheOrganization: 'Name of the organization',
                search: 'Search',
                startDate: 'Start Date',
                endDate: 'End Date',
                mainGuest: 'Main guest',
                additionalMembers: 'Additional members',
                notSelected: 'No selected'
            },
            eventTypes: {
                conference: "Conference",
                seminar: "Seminar",
                meeting: "Meeting",
                foreign: "Foreign event",
                diplomatic: "Diplomatic event",
                delegations: "Delegations",
                birthday: "Birthday",
                significant: "Significant date",
                personal: "Personal event"
            },
            crudNames: {
                event: 'event',
                document: 'document',
                translator: 'translator',
                administrator: 'administrator ',
                expert: 'expert',
                head: 'chief',
                project: 'project',
                agreement: 'agreement',
                report: 'report',
                organization: 'organization',
                employee: "employee"
            },
            tableTitles: {
                countries: 'Country',
                position: 'Position',
                meetings: 'Meetings',
                visits: 'Visits',
                date: 'Date', 
                name: 'Title', 
                place: 'Place',
                format: 'Format',
                level: 'Level',
                period: 'Period', 
                partners: 'Partners',
                donor: 'Donor',
                organizer: 'Organizer',
                additionalInfo: 'Additional Information',
                administrationsConsent: "Administration's Consent",
                placeOfSigning: 'Place of Signing',
                dateOfSigning: 'Date of Signing',
                files: 'Files',
                fullNameOfLeader: 'Full Name of the Head',
                nameOfTheProject: 'Project Name',
                nameOfMeeting: 'Meeting TitleName of the Meeting',
                nameOfDocument: 'Document title',
                mainAreas: 'Main areas',
                event: 'Event',
                fullName: 'Full Name',
                languages: 'Languages',
                rating: 'Rating',
                totalNumber: 'Total number',
                organizerAgency: 'Organizer Agency',
                otherOrganizer: 'Other organizer',
                totalEvents: 'Seminar/Training/Conference/Forum',
                internationalOrganization: 'International organization',
                numberOfVisits: 'Number of visits',
                agency: 'Agency',
                type: 'Type',
                responsiblePerson: 'Responsible person',
                creationDate: 'Creation date',
                actions: 'Actions',
                typeOfOrganization: 'Type of organization',
                comment: 'Comment',
                total: 'Total',
                other: 'Other',
                organization: 'Organization',
                endDate: 'End date',
                eventType: 'Event type',
            },
            tablesName: {
                events: 'Events',
                visits: 'Visits',
                internationalDocuments: 'International Documents',
                leaders : 'Leaders ',
                jointProjects: 'Joint Projects',
                meetingTimeline: 'Meeting Timeline',
                countryVisitStatistics: 'Country visit statistics',
                staffVisitStatistics: 'Staff visit statistics',
                year: 'year',
                for: 'for',
                listOfEventsWithType: 'List of events with type',
                byLevel: 'by level',
                partnersStatistics: 'Partners statistics',
            },
            roles: {
                admin: "Administrator",
                intl_officer: "International Officer",
                junior_intl_officer: "Junior International Officer",
                manager: "Manager",
                employee: "Employee"
            },
            calendar: {
                today: "Today",
                previous: "Back",
                next: "Next",
                month: "Month",
                week: "Week",
                day: "Day",
                date: "Date",
                time: "Time",
                event: "Event",
                noEventsInRange: "No events in this range",
                sunday: "Sunday",
                monday: "Monday",
                tuesday: "Tuesday",
                wednesday: "Wednesday",
                thursday: "Thursday",
                friday: "Friday",
                saturday: "Saturday",
                dateRangeLabel: "From {{start}} to {{end}}"
            },
            typeOfReport:{
                weekly: 'Weekly',
                monthly: 'Monthly',
                quarterly: 'Quarterly',
                semiAnnual: 'Semi-annual',
                annual: 'Annual ',
            }
        }
    },
    ru:{translation:{
        messages: {
            eventDeleted: "Мероприятие успешно удалено",
            eventDeleteError: "Ошибка при удалении мероприятия",
            employeeCreatedSuccess: "Сотрудник добавлен успешно",
            employeeCreatedError: "Ошибка при создании сотрудника",
            serverError: "Ошибка сервера",
            employeeUpdatedSuccess: "Сотрудник успешно обновлен",
            employeeUpdatedError: "Ошибка при обновлении сотрудника",
            employeeDeletedSuccess: "Сотрудник успешно удален",
            employeeDeletedError: "Ошибка при удалении сотрудника",
            projectUpdatedSuccess: "Проект успешно обновлен",
            projectUpdatedError: "Ошибка при обновлении проекта",
            projectCreatedSuccess: "Проект добавлен успешно",
            projectCreatedError: "Ошибка при создании проекта",
            projectDeletedSuccess: "Проект успешно удален",
            projectDeletedError: "Ошибка при удалении проекта",
            fileIdNotFound: "Айди файла не найдено",
            fileDeletedSuccess: "Файл удален успешно",
            eventCreatedSuccess: "Мероприятие было добавлено успешно",
            eventCreatedError: "Ошибка при добавлении мероприятия",
            eventAddedSuccess: "Мероприятие было добавлено успешно",
            eventAddError: "Ошибка при добавлении мероприятия",
            eventUpdatedSuccess: "Мероприятие успешно обновлено",
            eventUpdateError: "Ошибка при обновлении мероприятия",
            userAddedSuccess: "Пользователь добавлен успешно",
            userRegisterError: "Ошибка при регистрации пользователя",
            serUpdatedSuccess: "Пользователь успешно обновлен",
            userUpdateError: "Ошибка при обновлении пользователя",
            userDeletedSuccess: "Пользователь успешно удален",
            userDeleteError: "Ошибка при удалении пользователя",
            documentAddedSuccess: "Документ добавлен успешно",
            documentCreateError: "Ошибка при создании документа",
            documentUpdatedSuccess: "Документ успешно обновлен",
            documentUpdateError: "Ошибка при обновлении документа",
            documentDeletedSuccess: "Документ успешно удален",
            documentDeleteError: "ошибка при удалении документа",
            expertAddedSuccess: "Эксперт добавлен успешно",
            expertCreateError: "Ошибка при создании эксперта",
            expertUpdatedSuccess: "Эксперт успешно обновлен",
            expertUpdateError: "Ошибка при обновлении эксперта",
            expertDeletedSuccess: "Эксперт успешно удален",
            expertDeleteError: "Ошибка при удалении эксперта",
            employeeAddedSuccess: "Сотрудник добавлен успешно",
            employeeCreateError: "Ошибка при создании сотрудника",
            employeeUpdateError: "Ошибка при обновлении сотрудника",
            employeeDeleteError: "Ошибка при удалении сотрудника",
            projectAddedSuccess: "Проект добавлен успешно",
            projectCreateError: "Ошибка при создании проекта",
            projectUpdateError: "Ошибка при обновлении проекта",
            projectDeleteError: "Ошибка при удалении проекта",
            organizationAddedSuccess: "Организация добавлена успешно",
            organizationCreateError: "Ошибка при создании организации",
            organizationUpdatedSuccess: "Организация успешно обновлена",
            organizationUpdateError: "Ошибка при обновлении организации",
            organizationDeletedSuccess: "Организация успешно удалена",
            organizationDeleteError: "Ошибка при удалении организации",
            contractAddedSuccess: "Договор добавлен успешно",
            contractCreateError: "Ошибка при создании договора",
            contractUpdatedSuccess: "Договор успешно обновлен",
            contractUpdateError: "Ошибка при обновлении договора",
            contractDeletedSuccess: "Договор успешно удален",
            contractDeleteError: "Ошибка при удалении договора",
            loginSuccess: "Успешный вход",
            reportAddedSuccess: "Отчет добавлен успешно",
            reportCreateError: "Ошибка при создании отчета",
            reportUpdatedSuccess: "Отчет успешно обновлен",
            reportUpdateError: "Ошибка при обновлении отчета",
            reportDeletedSuccess: "Отчет успешно удален",
            reportDeleteError: "Ошибка при удалении отчета",
            translatorAddedSuccess: "Переводчик добавлен успешно",
            translatorCreateError: "Ошибка при создании переводчика",
            translatorUpdatedSuccess: "Переводчик успешно обновлен",
            translatorUpdateError: "Ошибка при обновлении переводчика",
            translatorDeletedSuccess: "Переводчик успешно удален",
            translatorDeleteError: "Ошибка при удалении переводчика"
        },
        navigation: {
            main: 'Главная',
            cooperation: 'Сотрудничество',
            countries: 'Страны',
            internationalOrganizations: 'Международные организации',
            internationalNonGovernmentalOrganizations: 'Международные неправительственные организации',
            internationalDocuments: 'Международные документы',
            internationalTreaties: 'Международные договора',
            experts: 'Эксперты',
            translators: 'Переводчики',
            eventStatistics: 'Статистика',
            events: 'Мероприятия',
            visits: 'Визиты',
            reports: 'Отчеты',
            administrations: 'Администрирование',
            employees: 'Сотрудники'
        },
        titles: {
            main: 'Главная',
            administration: 'Администрирование',
            cooperation: 'Сотрудничество',
            countries: 'Страны',
            eventStatistics: 'Статистика мероприятий',
            experts: 'Эксперты',
            internationalDocuments: 'Международные документы',
            internationalNonGovernmentalOrganizations: 'Международные не правительственные организации',
            internationalOrganizations: 'Международные организации',
            internationalsTreaties: 'Международные договора',
            reports: 'Отчеты',
            statistics: 'Статистика',
            statisticsOfCountryVisits: 'Статистика визитов стран',
            translators: 'Переводчики',
            visitsEmployees: 'Статистика визитов сотрудников',
            areYouSure: 'Вы точно хотите удалить',
            administrator: 'Администратор',
            overallStatistics: 'Общая статистика',
            totalMeetings: 'Всего встреч',
            Agency: 'Агентство',
            otherOrganizer: 'Другой организатор	',
            expertLevel: 'Экспертный',
            organizations: 'Организации',
            countryOrOrganization: 'Страна / Организация',
            conferenceFormat: 'Формат конференции',
            roles: {
                director: "Директор",
                deputy: "Заместитель",
                expert: "Эксперт",
                organizer: 'Орзанизатор'
            }

        },
        buttons: {
            back: 'Назад',
            today: 'Сегодня',
            forward: 'Вперёд',
            month: 'Месяц',
            week:'Неделя',
            day: 'День',
            excelDownload: 'Скачать Excel',
            worldDownload: 'Скачать Word',
            print: 'Печать',
            create: 'Создать',
            edit: 'Изменить',
            delete: 'Удалить',
            retrieve: 'Просмотреть',
            add: 'Добавить',
            actions: 'Действия',
            cancel: 'Отменить',
            login: 'Вход',
            logout: 'Выход',
            addAnotherFile: 'Добавить еще файл',
            addAnotherDate: 'Добавить еще дату',
            addAnotherCV: 'Добавить еще CV',
            addAnotherCertificate:'Добавить еще справку',
            addAnotherDocument: 'Добавить еще документ',
            otherCountry: 'Другая страна',
            otherGovernmentBody: 'Другой Гос.орган',
            addLang: 'Добавить язык	',
            selectYear: 'Выбрать год',
            addReport: 'Добавить отчет',
            download: 'Скачать',
            active: 'Активный',
            inactive: 'Не активный',
            sort: {
                sortBy: 'Сортировать по',
                byName: 'По названию',
                byVisit: 'По визиту',
                byMeeting: 'По встрече',
                all: 'Все',
                agency: 'Агентство',
                otherOrganizer: 'Другой организатор	',	
            }
        },
        events:{
            conference: 'Конференция / Форум',
            birthday: '	Дни рождения',
            delegations: 'Прием делегаций',
            diplomatic: 'Дипломатические приемы',
            foreign: 'Иностранные визиты',
            meeting: 'Встреча / Совещание',
            personal: 'Личне вопросы',
            seminar: 'Семинар/Тренинг ',
            significant: 'Значимые события',
            other: 'Другое',
            online: 'Онлайн',
            offline: 'Офлайн',
            letterToMFA: 'Письмо в МИД',
            MFAResponse	: 'Ответ МИД',
            approvalFromMFA: 'Согласование от МИД',
            letterToSSS: 'Письмо в СГБ', 
            SSSResponse: 'Ответ СГБ', 
            approvalFromSSS: 'Согласование от СГБ', 
            letterToAdministration: 'Письмо в Администрацию', 
            administrationResponse: 'Ответ Администрации', 
            approvalFromAdministration: 'Согласование от Администрации', 
            foreignVisits: 'Зарубежные визиты',
            receptionOfDelegations: 'Прием делегаций',
            diplomaticReceptions: 'Дипломатические приёмы',
            hybrid: "Гибридный",
            membersQuantity: 'Количество участников',
        },
        inputs: {
            selectEvent: 'Выберите мероприятие',
            enterOrganizer: 'Введите организатора',
            selectFormat: 'Выберите формат',
            numberOfParticipants: 'Кол-во участников',
            selectPartner: 'Выберите партнера',
            selectDonor: 'Выберите донора',
            number: 'Номер',
            selectDate: 'Выберите дату',
            title: 'Название',
            enterTitle: 'Введите название',
            uploadFile: 'Загрузите файл',
            placeOfSigning: 'Место подписания',
            enterFullName: 'Введите Ф.И.О',
            additionalInformation: 'Дополнительная информация',
            uploadCV: 'Загрузить CV',
            uploadCertificate: 'Загрузите справку',
            uploadScannedDocument: 'Загрузить сканер документа',
            governmentBody: 'Гос.орган',
            nameOfGovernmentBody: 'Название Гос.органа',
            administrationsPermission: 'Разрешение администрации',
            contractTitle: 'Название договора',
            levelOfSigning: 'Уровень подписания',
            mainAreas: 'Основные сферы',
            invitingOrganization: 'Привлекающая организация',
            selectLanguage: 'Выберите язык',
            points: 'Балы',
            responsible: 'Ответственный',
            name: 'Имя',
            role: 'Роль',
            status: 'Статус',
            lastLogin: 'Последний вход',
            lastName: 'Фамилия',
            phone: 'Номер телефона',
            email: 'Почта',
            password: 'Пароль',
            nameOfTheOrganization: 'Название организации',
            search: 'Поиск',
            startDate: 'Начало даты',
            endDate: 'Конец даты',
            mainGuest: 'Главный гость',
            additionalMembers: 'дополнительные участники',
            notSelected: "Не выбрано"
        },
        crudNames: {
            event: 'мероприятие',
            document: 'документ',
            translator: 'переводчика',
            administrator: 'администратора',
            expert: 'эксперта',
            head: 'главу',
            project: 'проект',
            agreement: 'договор',
            report: 'отчет',
            organization: 'oрганизацию',
            employee: "сотрудника"
        },
        tableTitles: {
            countries: 'Страна',
            position: 'Должность',
            meetings: 'Встречи',
            visits: 'Визиты',
            date: 'Дата', 
            name: 'Название', 
            place: 'Место',
            format: 'Формат',
            level: 'Уровень',
            period: 'Период', 
            donor: 'Донор',
            partners: 'Партнеры',
            organizer: 'Организатор',
            additionalInfo: 'Доп.Информация',
            administrationsConsent: 'Соглание администрации',
            placeOfSigning: 'Место подписания',
            dateOfSigning: 'Дата подписания',
            files: 'Файлы',
            fullNameOfLeader: 'Ф.И.О Главы',
            nameOfTheProject: 'Название проекта',
            nameOfMeeting: 'Название встречи',
            nameOfDocument: 'Название документа',
            mainAreas: 'Основные сферы',
            event: 'Мероприятие',
            fullName: 'Ф.И.О',
            languages: 'Языки',
            rating: 'Рейтинг',
            totalNumber: 'Общее количество',
            organizerAgency: 'Организатор Агентство',
            otherOrganizer: 'Другой организатор',
            totalEvents: 'Семинар/Тренинг/Конференция/Форум',
            internationalOrganization: 'Международная организация',
            numberOfVisits: 'Количество визитов',
            agency: 'Агентство',
            type: 'Тип',
            responsiblePerson: 'Ответственный',
            creationDate: 'Дата создания',
            actions: 'Действия',
            typeOfOrganization: 'Тип организации',
            organization: 'Организация',
            comment: 'Комментарий',
            total: 'Всего',
            other: 'Другой',
            endDate: 'Дата окончания',
            eventType: 'Тип мероприятия',
        },
        eventTypes: {
            conference: "Конференция",
            seminar: "Семинар",
            meeting: "Встреча",
            foreign: "Зарубежное мероприятие",
            diplomatic: "Дипломатическое мероприятие",
            delegations: "Делегации",
            birthday: "День рождения",
            significant: "Значимая дата",
            personal: "Личное мероприятие"
        },
        tablesName: {
            events: 'Мероприятия',
            visits: 'Визиты',
            internationalDocuments: 'Международные документы',
            leaders : 'Главы',
            jointProjects: 'Совместные проекты',
            meetingTimeline: 'Хронология встреч',
            countryVisitStatistics: 'Статистика визитов стран',
            staffVisitStatistics: 'Статистика визитов сотрудников',
            year: 'год',
            for: 'за',
            listOfEventsWithType: 'Список мероприятий с типом',
            byLevel: 'по уровню',
            partnersStatistics: 'Статистика партнеров',
        },
        calendar: {
            today: "Сегодня",
            previous: "Назад",
            next: "Вперёд",
            month: "Месяц",
            week: "Неделя",
            day: "День",
            date: "Дата",
            time: "Время",
            event: "Событие",
            noEventsInRange: "Нет событий в этом диапазоне",
            sunday: "Воскресенье",
            monday: "Понедельник",
            tuesday: "Вторник",
            wednesday: "Среда",
            thursday: "Четверг",
            friday: "Пятница",
            saturday: "Суббота",
            dateRangeLabel: "С {{start}} по {{end}}"
        },
        roles: {
            admin: "Администратор",
            intl_officer: "Международный сотрудник",
            junior_intl_officer: "Младший международный сотрудник",
            manager: "Менеджер",
            employee: "Сотрудник"
        },
        typeOfReport:{
            weekly: 'Недельный',
            monthly: 'Месячный',
            quarterly: 'Квартальный',
            semiAnnual: 'Полу-годовой	',
            annual: 'Годовой',
        }
    }},
    uz:{
        translation:{
            messages: {
                eventDeleted: "Tadbir muvaffaqiyatli o‘chirildi",
                eventDeleteError: "Tadbirni o‘chirishda xatolik yuz berdi",
                employeeCreatedSuccess: "Xodim muvaffaqiyatli qo‘shildi",
                employeeCreatedError: "Xodimni yaratishda xatolik yuz berdi",
                serverError: "Server xatosi",
                employeeUpdatedSuccess: "Xodim muvaffaqiyatli yangilandi",
                employeeUpdatedError: "Xodimni yangilashda xatolik yuz berdi",
                employeeDeletedSuccess: "Xodim muvaffaqiyatli o‘chirildi",
                employeeDeletedError: "Xodimni o‘chirishda xatolik yuz berdi",
                projectUpdatedSuccess: "Loyiha muvaffaqiyatli yangilandi",
                projectUpdatedError: "Loyihani yangilashda xatolik yuz berdi",
                projectCreatedSuccess: "Loyiha muvaffaqiyatli qo‘shildi",
                projectCreatedError: "Loyihani yaratishda xatolik yuz berdi",
                projectDeletedSuccess: "Loyiha muvaffaqiyatli o‘chirildi",
                projectDeletedError: "Loyihani o‘chirishda xatolik yuz berdi",
                fileIdNotFound: "Fayl ID topilmadi",
                fileDeletedSuccess: "Fayl muvaffaqiyatli o‘chirildi",
                eventCreatedSuccess: "Tadbir muvaffaqiyatli qo‘shildi",
                eventCreatedError: "Tadbirni qo‘shishda xatolik yuz berdi",
                eventAddedSuccess: "Tadbir muvaffaqiyatli qoʻshildi",
                eventAddError: "Tadbirni qoʻshishda xatolik",
                eventUpdatedSuccess: "Tadbir muvaffaqiyatli yangilandi",
                eventUpdateError: "Tadbirni yangilashda xatolik",
                userAddedSuccess: "Foydalanuvchi muvaffaqiyatli qoʻshildi",
                userRegisterError: "Foydalanuvchini roʻyxatdan oʻtkazishda xatolik",
                userUpdatedSuccess: "Foydalanuvchi muvaffaqiyatli yangilandi",
                userUpdateError: "Foydalanuvchini yangilashda xatolik",
                userDeletedSuccess: "Foydalanuvchi muvaffaqiyatli oʻchirildi",
                userDeleteError: "Foydalanuvchini oʻchirishda xatolik",
                documentAddedSuccess: "Hujjat muvaffaqiyatli qoʻshildi",
                documentCreateError: "Hujjat yaratishda xatolik",
                documentUpdatedSuccess: "Hujjat muvaffaqiyatli yangilandi",
                documentUpdateError: "Hujjatni yangilashda xatolik",
                documentDeletedSuccess: "Hujjat muvaffaqiyatli oʻchirildi",
                documentDeleteError: "Hujjatni o‘chirishda xatolik yuz berdi",
                expertAddedSuccess: "Ekspert muvaffaqiyatli qoʻshildi",
                expertCreateError: "Ekspert yaratishda xatolik",
                expertUpdatedSuccess: "Ekspert muvaffaqiyatli yangilandi",
                expertUpdateError: "Ekspertni yangilashda xatolik",
                expertDeletedSuccess: "Ekspert muvaffaqiyatli oʻchirildi",
                expertDeleteError: "Ekspertni oʻchirishda xatolik",
                employeeAddedSuccess: "Xodim muvaffaqiyatli qoʻshildi",
                employeeCreateError: "Xodim yaratishda xatolik",
                employeeUpdateError: "Xodimni yangilashda xatolik",
                employeeDeleteError: "Xodimni oʻchirishda xatolik",
                projectAddedSuccess: "Loyiha muvaffaqiyatli qoʻshildi",
                projectCreateError: "Loyihani yaratishda xatolik",
                projectUpdateError: "Loyihani yangilashda xatolik",
                projectDeleteError: "Loyihani oʻchirishda xatolik",
                organizationAddedSuccess: "Tashkilot muvaffaqiyatli qoʻshildi",
                organizationCreateError: "Tashkilotni yaratishda xatolik",
                organizationUpdatedSuccess: "Tashkilot muvaffaqiyatli yangilandi",
                organizationUpdateError: "Tashkilotni yangilashda xatolik",
                organizationDeletedSuccess: "Tashkilot muvaffaqiyatli oʻchirildi",
                organizationDeleteError: "Tashkilotni oʻchirishda xatolik",
                contractAddedSuccess: "Shartnoma muvaffaqiyatli qoʻshildi",
                contractCreateError: "Shartnomani yaratishda xatolik",
                contractUpdatedSuccess: "Shartnoma muvaffaqiyatli yangilandi",
                contractUpdateError: "Shartnomani yangilashda xatolik",
                contractDeletedSuccess: "Shartnoma muvaffaqiyatli oʻchirildi",
                contractDeleteError: "Shartnomani oʻchirishda xatolik",
                loginSuccess: "Muvaffaqiyatli tizimga kirildi",
                reportAddedSuccess: "Hisobot muvaffaqiyatli qoʻshildi",
                reportCreateError: "Hisobot yaratishda xatolik",
                reportUpdatedSuccess: "Hisobot muvaffaqiyatli yangilandi",
                reportUpdateError: "Hisobotni yangilashda xatolik",
                reportDeletedSuccess: "Hisobot muvaffaqiyatli oʻchirildi",
                reportDeleteError: "Hisobotni oʻchirishda xatolik",
                translatorAddedSuccess: "Tarjimon muvaffaqiyatli qoʻshildi",
                translatorCreateError: "Tarjimon yaratishda xatolik",
                translatorUpdatedSuccess: "Tarjimon muvaffaqiyatli yangilandi",
                translatorUpdateError: "Tarjimonni yangilashda xatolik",
                translatorDeletedSuccess: "Tarjimon muvaffaqiyatli oʻchirildi",
                translatorDeleteError: "Tarjimonni oʻchirishda xatolik"
            },
            navigation: {
                main: 'Bosh sahifa',
                cooperation: 'Hamkorlik',
                countries: 'Mamlakatlar',
                internationalOrganizations: 'Xalqaro tashkilotlar',
                internationalNonGovernmentalOrganizations: 'Xalqaro nodavlat tashkilotlar',
                internationalDocuments: 'Xalqaro hujjatlar',
                internationalTreaties: 'Xalqaro shartnomalar',
                experts: 'Mutaxassislar',
                translators: 'Tarjimonlar',
                eventStatistics: 'Statistika',
                visits: 'Tadbirlar',
                events: 'Tashriflar',
                reports: 'Hisobotlar',
                administrations: 'Ma’muriyat',
                employees: 'Hodimlar'
            },
            titles: {
                main: 'Bosh sahifa',
                administration: 'Ma’muriyat',
                cooperation: 'Hamkorlik',
                countries: 'Mamlakatlar',
                eventStatistics: 'Tadbirlar statistikasi',
                experts: 'Mutaxassislar',
                internationalDocuments: 'Xalqaro hujjatlar',
                internationalNonGovernmentalOrganizations: 'Xalqaro nodavlat tashkilotlar',
                internationalOrganizations: 'Xalqaro tashkilotlar',
                internationalsTreaties: 'Xalqaro shartnomalar',
                reports: 'Hisobotlar',
                statistics: 'Statistika',
                statisticsOfCountryVisits: 'Mamlakatlarga tashriflar statistikasi',
                translators: 'Tarjimonlar',
                visitsEmployees: 'Hodimlar tashriflari statistikasi',
                areYouSure: "O'chirishni xohlaysizmi",
                administrator: 'Administrator',
                overallStatistics: 'Umumiy statistika',
                totalMeetings: 'Umumiy uchrashuvlar',
                Agency: 'Agentlik',
                otherOrganizer: 'Boshqa tashkilotchi',
                expertLevel: 'Ekspert darajasidagi',
                organizations: 'Tashkilotlar',
                countryOrOrganization: 'Mamlakat / Tashkilot',
                conferenceFormat: 'Konferensiya formati',
                roles: {
                    director: "Direktor",
                    deputy: "Muovini",
                    expert: "Mutaxassis",
                    organizer: 'Tashkilotchi'
                }
            },
            buttons: {
                back: 'Orqaga',
                today: 'Bugun',
                forward: 'Oldinga',
                month: 'Oy',
                week:'Hafta',
                day: 'Kun',
                excelDownload: 'Excel yuklab olish',
                worldDownload: 'Word yuklab olish',
                print: 'Chop etish',
                create: 'Yaratish',
                edit: 'Tahrirlash',
                delete: "O'chirish",
                retrieve: 'Ko‘rish',
                add: 'Qo‘shish',
                actions: 'Harakatlar',
                cancel: 'Bekor qilish',
                login: 'Kirish',
                logout: 'Chiqish',
                addAnotherFile: 'Yana fayl qo‘shish',
                addAnotherDate: 'Yana sana qo‘shish',
                addAnotherCV: 'Yana bir CV qo‘shish',
                addAnotherCertificate:'Ma’lumotnomani yuklash',
                addAnotherDocument: 'Yana bir hujjat qo‘shish',
                otherCountry: 'Boshqa davlat',
                otherGovernmentBody: 'Boshqa davlat organi',
                addLang: 'Til qo‘shish',
                selectYear: 'Yilni tanlang',
                addReport: 'Hisobot qo‘shish',
                download: 'Yuklab olish',
                active: 'Faol',
                inactive: 'Nofaol',
                sort: {
                    sortBy: 'Saralash turi',
                    byName: 'Nomi bo‘yicha',
                    byVisit: 'Tashrif bo‘yicha',
                    byMeeting: 'Uchrashuv bo‘yicha',
                    all: 'Barchasi',
                    agency: 'Agentlik',
                    otherOrganizer: 'Boshqa tashkilotchi',	
                }
            },
            events:{
                conference: 'Konferensiya / Forum',
                birthday: 'Tug‘ilgan kunlar',
                delegations: 'Delegatsiyalarni qabul qilish',
                diplomatic: 'Diplomatik qabullar',
                foreign: 'Xorijiy tashriflar',
                meeting: 'Uchrashuv / Majlis',
                personal: 'Shaxsiy masalalar',
                seminar: 'Seminar / Trening',
                significant: 'Muhim voqealar',
                other: 'Boshqa',
                online: 'Onlayn',
                offline: 'Offline',
                letterToMFA: 'TIVga xat',
                MFAResponse: 'TIVdan javob',
                approvalFromMFA: 'TIVdan kelgan kelishuv',
                letterToSSS: 'DXXga xat',
                SSSResponse: 'DXXdan javob',
                approvalFromSSS: 'DXXdan kelgan kelishuv',
                letterToAdministration: 'Administratsiyaga xat',
                administrationResponse: 'Administratsiyadan javob',
                approvalFromAdministration: 'Administratsiyadan kelgan kelishuv',
                foreignVisits: 'Chet el safarlari',
                receptionOfDelegations: 'Delegatsiyalarni qabul qilish',
                diplomaticReceptions: 'Diplomatik qabul marosimlari',
                hybrid: "Gibrid",
                membersQuantity: "A'zolar soni",
            },
            inputs: {
                selectEvent: 'Tadbirni tanlang',
                enterOrganizer: 'Tashkilotchini kiriting',
                selectFormat: 'Formatni tanlang',
                numberOfParticipants: 'Ishtirokchilar soni',
                selectPartner: 'Hamkorni tanlang',
                selectDonor: 'Donorni tanlang',
                number: 'Raqam',
                selectDate: 'Sanani tanlang',
                title: 'Nomi',
                uploadFile: 'Fayl yuklash',
                placeOfSigning: 'Imzolangan joy',
                enterTitle: 'Nomini kiriting',
                enterFullName: 'F.I.O.ni kiriting',
                additionalInformation: 'Qo‘shimcha ma’lumot',
                uploadCV: 'CV yuklash',
                uploadCertificate: 'Ma’lumotnomani yuklash',
                uploadScannedDocument: 'Hujjat skanerini yuklash',
                governmentBody: 'Davlat organi',
                nameOfGovernmentBody: 'Davlat organi nomi',
                administrationsPermission: 'Ma’muriyat ruxsati',
                contractTitle: 'Shartnoma nomi',
                levelOfSigning: 'Imzolash darajasi',
                mainAreas: 'Asosiy sohalar',
                invitingOrganization: 'Jalb qiluvchi tashkilot',
                selectLanguage: 'Tilni tanlang',
                points: 'Ballar',
                responsible: "Mas'ul",
                name: 'Ism',
                role: 'Rol',
                status: 'Holat',
                lastLogin: 'Oxirgi kirish',
                lastName: 'Familiya',
                phone: 'Telefon raqami',
                email: 'Elektron pochta',
                password: 'Parol',
                nameOfTheOrganization: 'Tashkilot nomi',
                search: 'Qidiruv',
                startDate: 'Sana boshlanishi',
                endDate: 'Sana tugashi',
                mainGuest: 'Asosiy mehmon',
                additionalMembers: 'Qo‘shimcha ishtirokchilar',
                notSelected: 'Tanlanmagan'
            },
            crudNames: {
                event: 'tadbir',
                document: 'hujjat',
                translator: 'tarjimon',
                administrator: 'administrator ',
                expert: 'mutaxassis',
                head: 'rahbar',
                project: 'loyihа',
                agreement: 'shartnoma',
                report: 'hisobot',
                organization: 'tashkilotni',
                employee: 'xodim'
            },
            tableTitles: {
                countries: 'Mamlakat',
                meetings: 'Uchrashuvlar',
                position: 'Lavozim ',
                visits: 'Tashriflar',
                date: 'Sana', 
                name: 'Nomi', 
                place: 'Joy',
                format: 'Format',
                level: 'Daraja',
                period: 'Davr', 
                donor: 'Donor',
                partners: 'Hamkorlar',
                organizer: 'Tashkilotchi',
                additionalInfo: "Qo'shimcha Ma'lumot",
                administrationsConsent: "Ma'muriyatning Roziligi",
                placeOfSigning: "Imzo qo'yish joyi",
                dateOfSigning: "Imzo qo'yish sanasi",
                files: 'Fayllar',
                fullNameOfLeader: 'Rahbarning F.I.Sh.',
                nameOfTheProject: 'Loyiha nomi',
                nameOfMeeting: 'Uchrashuv nomi',
                nameOfDocument: 'Hujjat nomi',
                mainAreas: 'Asosiy sohalar',
                event: 'Tadbir',
                fullName: 'F.I.O.',
                languages: 'Tillar',
                rating: 'Reyting',
                totalNumber: 'Umumiy miqdor',
                organizerAgency: 'Tashkilotchi agentlik',
                otherOrganizer: 'Boshqa tashkilotchi',
                totalEvents: 'Seminar/Trening/Konferensiya/Forum',
                internationalOrganization: 'Xalqaro tashkilot',
                numberOfVisits: 'Tashriflar soni',
                agency: 'Agentlik',
                type: 'Turi',
                responsiblePerson: "Mas'ul shaxs",
                creationDate: 'Yaratilgan sana',
                actions: 'Harakatlar',
                typeOfOrganization: 'Tashkilot turi',
                comment: 'Izoh',
                total: 'Jami',
                other: 'Boshqalar',
                organization: 'Tashkilot',
                endDate: 'Tugash sanasi',
                eventType: 'Tadbir turi',
            },
            eventTypes: {
                conference: "Konferensiya",
                seminar: "Seminar",
                meeting: "Uchrashuv",
                foreign: "Xorijiy tadbir",
                diplomatic: "Diplomatik tadbir",
                delegations: "Delegatsiyalar",
                birthday: "Tug‘ilgan kun",
                significant: "Muhim sana",
                personal: "Shaxsiy tadbir"
            },
            tablesName: {
                events: 'Tadbirlar',
                visits: 'Tashriflar',
                internationalDocuments: 'Xalqaro hujjatlar',
                leaders : 'Rahbarlar',
                jointProjects: 'Hamkorlik loyihalari',
                meetingTimeline: 'Uchrashuvlar xronologiyasi',
                countryVisitStatistics: 'Mamlakat tashriflari statistikasi',
                staffVisitStatistics: 'Xodimlar tashriflari statistikasi',
                year: 'yil',
                for: 'uchun',
                listOfEventsWithType: 'Turi bo‘yicha tadbirlar ro‘yxati',
                byLevel: 'darajasi bo‘yicha',
                partnersStatistics: 'Hamkorlar statistikasi',
            },
            roles: {
                admin: "Administrator",
                intl_officer: "Xalqaro ofitser",
                junior_intl_officer: "Kichik xalqaro ofitser",
                manager: "Menejer",
                employee: "Xodim"
            },
            calendar: {
                today: "Bugun",
                previous: "Oldingi",
                next: "Keyingi",
                month: "Oy",
                week: "Hafta",
                day: "Kun",
                date: "Sana",
                time: "Vaqt",
                event: "Tadbir",
                noEventsInRange: "Bu oraliqda tadbirlar yo‘q",
                sunday: "Yakshanba",
                monday: "Dushanba",
                tuesday: "Seshanba",
                wednesday: "Chorshanba",
                thursday: "Payshanba",
                friday: "Juma",
                saturday: "Shanba",
                dateRangeLabel: "{{start}} dan {{end}} gacha"
            },
            typeOfReport:{
                weekly: 'Haftalik',
                monthly: 'Oylik',
                quarterly: 'Choraklik',
                semiAnnual: 'Yarim yillik',
                annual: 'Yillik',
            }
    }}
}