export const resources = {
    en:{
        translation:{
            navigation: {
                main: 'Home',
                cooperation: 'Cooperation',
                countries: 'Countries',
                internationalOrganizations: 'International organizations',
                internationalNonGovernmentalOrganizations: 'International Non-Governmental Organizations',
                internationalDocuments: 'International Documents',
                internationalTreaties: 'International Agreements',
                experts: 'Experts',
                translators: 'Translators',
                eventStatistics: 'Statistics',
                events: 'Events',
                visits: 'Visits',
                reports: 'Reports',
                administrations: 'Administration',
                employees: 'Employees'
            },
            titles: {
                main: 'Home',
                administration: 'Administration',
                cooperation: 'Cooperation',
                countries: 'Countries',
                eventStatistics: 'Event Statistics	',
                experts: 'Experts',
                internationalDocuments: 'International Documents',
                internationalNonGovernmentalOrganizations: 'International Non-Governmental Organizations',
                internationalOrganizations: 'International Organizations',
                internationalsTreaties: 'International Agreements',
                reports: 'Reports',
                statistics: 'Statistics',
                statisticsOfCountryVisits: 'Country Visit Statistics',
                translators: 'Translators',
                visitsEmployees: 'Employee Visit Statistics',
                areYouSure: 'Are you sure you want to delete',
                administrator: 'Administrator',
                overallStatistics: 'Overall statistics',
                totalMeetings: 'Total meetings',
                Agency: 'Agency',
                otherOrganizer: 'Other organizer',
                expertLevel: 'Expert-level',
                organizations: 'Organizations'
            },
            buttons: {
                back: 'Back',
                today: 'Today   ',
                forward: 'Forward',
                month: 'Month',
                week:'Week',
                day: 'Day',
                excelDownload: 'Download Excel',
                worldDownload: 'Download Word',
                print: 'Print',
                create: 'Create',
                edit: 'Edit',
                delete: 'Delete',
                retrieve: 'View',
                add: 'Add',
                actions: 'Actions',
                cancel: 'Cancel',
                login: 'Login',
                logout: 'Logout',
                addAnotherFile: 'Add another file',
                addAnotherDate: 'Add another date',
                addAnotherCV: 'Add another CV',
                addAnotherCertificate:'Upload certificate',
                addAnotherDocument: 'Add another document',
                otherCountry: 'Other country',
                otherGovernmentBody: '	Other government body',
                addLang: 'Add language',
                selectYear: 'Select year',
                addReport: 'Add report',
                download: 'Download',
                active: 'Active',
                inactive: 'Inactive',
                sort: {
                    sortBy: 'Sort by',
                    byName: 'By name',
                    byVisit: 'By visit',
                    byMeeting: 'By meeting	',
                    all: 'All',
                    agency: 'Agency',
                    otherOrganizer: 'Other organizer',	
                }

            },
            events:{
                conferences: 'Conferences/Forums',
                seminar: 'Seminar/Training',
                meetings: 'Meetings',
                partners: 'Partners',
                other: 'Other',
                online: 'Online',
                offline: 'Offline',
                letterToMFA: 'Letter to MFA',
                MFAResponse	: 'MFA Response',
                approvalFromMFA: 'Approval from MFA' ,
                letterToSSS: 'Letter to SSS',
                SSSResponse: 'SSS Response',
                approvalFromSSS: 'Approval from SSS',
                letterToAdministration: 'Letter to Administration',
                administrationResponse: 'Administration Response',
                approvalFromAdministration: 'Approval from Administration',
                foreignVisits: 'Foreign visits',
                receptionOfDelegations: 'Reception of delegations',
                diplomaticReceptions: 'Diplomatic receptions',
            },
            inputs: {
                selectEvent: 'Select event',
                enterOrganizer: 'Enter organizer',
                selectFormat: 'Select format',
                numberOfParticipants: 'Number of participants',
                selectPartner: 'Select partner',
                selectDonor: 'Select donor',
                number: 'Number',
                selectDate: 'Select date',
                title: 'Title',
                uploadFile: 'Upload file',
                placeOfSigning: 'Place of signing',
                enterTitle: 'Enter title',
                enterFullName: 'Enter full name',
                additionalInformation: 'Additional information',
                uploadCV: 'Upload CV',
                uploadCertificate: 'Add another certificate',
                uploadScannedDocument: 'Upload scanned document',
                governmentBody: 'Government body',
                nameOfGovernmentBody: 'Name of government body',
                administrationsPermission: 'Administration’s permission',
                contractTitle: 'Contract title',
                levelOfSigning: 'Level of signing',
                mainAreas: 'Main areas ',
                invitingOrganization: 'Inviting organization',
                selectLanguage: 'Select a language',
                points: 'Points',
                responsible: 'Responsible',
                name: 'Name',
                role: 'Role',
                status: 'Status',
                lastLogin: 'Last login',
                lastName: 'Last Name',
                phone: 'Phone Number',
                email: 'Email',
                password: 'Password',
                nameOfTheOrganization: 'Name of the organization',
                search: 'Search'
            },
            crudNames: {
                event: 'event',
                document: 'document',
                translator: 'translator',
                administrator: 'administrator ',
                expert: 'expert',
                head: 'chief',
                project: 'project',
                agreement: 'agreement',
                report: 'report',
                organization: 'organization',
                employee: "employee"
            },
            tableTitles: {
                countries: 'Country',
                position: 'Position',
                meetings: 'Meetings',
                visits: 'Visits',
                date: 'Date', 
                name: 'Title', 
                place: 'Place',
                format: 'Format',
                level: 'Level',
                period: 'Period', 
                donor: 'Donor',
                organizer: 'Organizer',
                additionalInfo: 'Additional Information',
                administrationsConsent: "Administration's Consent",
                placeOfSigning: 'Place of Signing',
                dateOfSigning: 'Date of Signing',
                files: 'Files',
                fullNameOfLeader: 'Full Name of the Head',
                nameOfTheProject: 'Project Name',
                nameOfMeeting: 'Meeting TitleName of the Meeting',
                nameOfDocument: 'Document title',
                mainAreas: 'Main areas',
                event: 'Event',
                fullName: 'Full Name',
                languages: 'Languages',
                rating: 'Rating',
                totalNumber: 'Total number',
                organizerAgency: 'Organizer Agency',
                otherOrganizer: 'Other organizer',
                totalEvents: 'Seminar/Training/Conference/Forum',
                internationalOrganization: 'International organization',
                numberOfVisits: 'Number of visits',
                agency: 'Agency',
                type: 'Type',
                responsiblePerson: 'Responsible person',
                creationDate: 'Creation date',
                actions: 'Actions',
                typeOfOrganization: 'Type of organization',
                comment: 'Comment'
            },
            tablesName: {
                events: 'Events',
                visits: 'Visits',
                internationalDocuments: 'International Documents',
                leaders : 'Leaders ',
                jointProjects: 'Joint Projects',
                meetingTimeline: 'Meeting Timeline',
                countryVisitStatistics: 'Country visit statistics',
                staffVisitStatistics: 'Staff visit statistics',
                year: 'year',
                for: 'for',
            },
            roles: {
                superAdministrator: 'Super Administrator',
                juniorAdministrator: 'Junior Administrator',
                user: 'User',
                administrator: 'Administrator'
            },
            typeOfReport:{
                weekly: 'Weekly',
                monthly: 'Monthly',
                quarterly: 'Quarterly',
                semiAnnual: 'Semi-annual',
                annual: 'Annual ',
            }
        }
    },
    ru:{translation:{
        navigation: {
            main: 'Главная',
            cooperation: 'Сотрудничество',
            countries: 'Страны',
            internationalOrganizations: 'Международные организации',
            internationalNonGovernmentalOrganizations: 'Международные неправительственные организации',
            internationalDocuments: 'Международные документы',
            internationalTreaties: 'Международные договора',
            experts: 'Эксперты',
            translators: 'Переводчики',
            eventStatistics: 'Статистика',
            events: 'Мероприятия',
            visits: 'Визиты',
            reports: 'Отчеты',
            administrations: 'Администрирование',
            employees: 'Сотрудники'
        },
        titles: {
            main: 'Главная',
            administration: 'Администрирование',
            cooperation: 'Сотрудничество',
            countries: 'Страны',
            eventStatistics: 'Статистика мероприятий',
            experts: 'Эксперты',
            internationalDocuments: 'Международные документы',
            internationalNonGovernmentalOrganizations: 'Международные не правительственные организации',
            internationalOrganizations: 'Международные организации',
            internationalsTreaties: 'Международные договора',
            reports: 'Отчеты',
            statistics: 'Статистика',
            statisticsOfCountryVisits: 'Статистика визитов стран',
            translators: 'Переводчики',
            visitsEmployees: 'Статистика визитов сотрудников',
            areYouSure: 'Вы точно хотите удалить',
            administrator: 'Администратор',
            overallStatistics: 'Общая статистика',
            totalMeetings: 'Всего встреч',
            Agency: 'Агентство',
            otherOrganizer: 'Другой организатор	',
            expertLevel: 'Экспертный',
            organizations: 'Организации'
        },
        buttons: {
            back: 'Назад',
            today: 'Сегодня',
            forward: 'Вперёд',
            month: 'Месяц',
            week:'Неделя',
            day: 'День',
            excelDownload: 'Скачать Excel',
            worldDownload: 'Скачать Word',
            print: 'Печать',
            create: 'Создать',
            edit: 'Изменить',
            delete: 'Удалить',
            retrieve: 'Просмотреть',
            add: 'Добавить',
            actions: 'Действия',
            cancel: 'Отменить',
            login: 'Вход',
            logout: 'Выход',
            addAnotherFile: 'Добавить еще файл',
            addAnotherDate: 'Добавить еще дату',
            addAnotherCV: 'Добавить еще CV',
            addAnotherCertificate:'Добавить еще справку',
            addAnotherDocument: 'Добавить еще документ',
            otherCountry: 'Другая страна',
            otherGovernmentBody: 'Другой Гос.орган',
            addLang: 'Добавить язык	',
            selectYear: 'Выбрать год',
            addReport: 'Добавить отчет',
            download: 'Скачать',
            active: 'Активный',
            inactive: 'Не активный',
            sort: {
                sortBy: 'Сортировать по',
                byName: 'По названию',
                byVisit: 'По визиту',
                byMeeting: 'По встрече',
                all: 'Все',
                agency: 'Агентство',
                otherOrganizer: 'Другой организатор	',	
            }
        },
        events:{
            conferences: 'Конференции/Форумы',
            seminar: 'Семинар/Тренинг',
            meetings: 'Встречи',
            partners: 'Партнеры',
            other: 'Другое',
            online: 'Онлайн',
            offline: 'Офлайн',
            letterToMFA: 'Письмо в МИД',
            MFAResponse	: 'Ответ МИД',
            approvalFromMFA: 'Согласование от МИД',
            letterToSSS: 'Письмо в СГБ', 
            SSSResponse: 'Ответ СГБ', 
            approvalFromSSS: 'Согласование от СГБ', 
            letterToAdministration: 'Письмо в Администрацию', 
            administrationResponse: 'Ответ Администрации', 
            approvalFromAdministration: 'Согласование от Администрации', 
            foreignVisits: 'Зарубежные визиты',
            receptionOfDelegations: 'Прием делегаций',
            diplomaticReceptions: 'Дипломатические приёмы',
        },
        inputs: {
            selectEvent: 'Выберите мероприятие',
            enterOrganizer: 'Введите организатора',
            selectFormat: 'Выберите формат',
            numberOfParticipants: 'Кол-во участников',
            selectPartner: 'Выберите партнера',
            selectDonor: 'Выберите донора',
            number: 'Номер',
            selectDate: 'Выберите дату',
            title: 'Название',
            enterTitle: 'Введите название',
            uploadFile: 'Загрузите файл',
            placeOfSigning: 'Место подписания',
            enterFullName: 'Введите Ф.И.О',
            additionalInformation: 'Дополнительная информация',
            uploadCV: 'Загрузить CV',
            uploadCertificate: 'Загрузите справку',
            uploadScannedDocument: 'Загрузить сканер документа',
            governmentBody: 'Гос.орган',
            nameOfGovernmentBody: 'Название Гос.органа',
            administrationsPermission: 'Разрешение администрации',
            contractTitle: 'Название договора',
            levelOfSigning: 'Уровень подписания',
            mainAreas: 'Основные сферы',
            invitingOrganization: 'Привлекающая организация',
            selectLanguage: 'Выберите язык',
            points: 'Балы',
            responsible: 'Ответственный',
            name: 'Имя',
            role: 'Роль',
            status: 'Статус',
            lastLogin: 'Последний вход',
            lastName: 'Фамилия',
            phone: 'Номер телефона',
            email: 'Почта',
            password: 'Пароль',
            nameOfTheOrganization: 'Название организации',
            search: 'поиск'
        },
        crudNames: {
            event: 'мероприятие',
            document: 'документ',
            translator: 'переводчика',
            administrator: 'администратора',
            expert: 'эксперта',
            head: 'главу',
            project: 'проект',
            agreement: 'договор',
            report: 'отчет',
            organization: 'oрганизацию',
            employee: "сотрудника"
        },
        tableTitles: {
            countries: 'Страна',
            position: 'Должность',
            meetings: 'Встречи',
            visits: 'Визиты',
            date: 'Дата', 
            name: 'Название', 
            place: 'Место',
            format: 'Формат',
            level: 'Уровень',
            period: 'Период', 
            donor: 'Донор',
            organizer: 'Организатор',
            additionalInfo: 'Доп.Информация',
            administrationsConsent: 'Соглание администрации',
            placeOfSigning: 'Место подписания',
            dateOfSigning: 'Дата подписания',
            files: 'Файлы',
            fullNameOfLeader: 'Ф.И.О Главы',
            nameOfTheProject: 'Название проекта',
            nameOfMeeting: 'Название встречи',
            nameOfDocument: 'Название документа',
            mainAreas: 'Основные сферы',
            event: 'Мероприятие',
            fullName: 'Ф.И.О',
            languages: 'Языки',
            rating: 'Рейтинг',
            totalNumber: 'Общее количество',
            organizerAgency: 'Организатор Агентство',
            otherOrganizer: 'Другой организатор',
            totalEvents: 'Семинар/Тренинг/Конференция/Форум',
            internationalOrganization: 'Международная организация',
            numberOfVisits: 'Количество визитов',
            agency: 'Агентство',
            type: 'Тип',
            responsiblePerson: 'Ответственный',
            creationDate: 'Дата создания',
            actions: 'Действия',
            typeOfOrganization: 'Тип организации',
            comment: 'Комментарий',
        },
        tablesName: {
            events: 'Мероприятия',
            visits: 'Визиты',
            internationalDocuments: 'Международные документы',
            leaders : 'Главы',
            jointProjects: 'Совместные проекты',
            meetingTimeline: 'Хронология встреч',
            countryVisitStatistics: 'Статистика визитов стран',
            staffVisitStatistics: 'Статистика визитов сотрудников',
            year: 'год',
            for: 'за',
        },
        roles: {
            superAdministrator: 'Супер администратор',
            juniorAdministrator: 'Младший администратор',
            user: 'Пользователь',
            administrator: 'Администратор'
        },
        typeOfReport:{
            weekly: 'Недельный',
            monthly: 'Месячный',
            quarterly: 'Квартальный',
            semiAnnual: 'Полу-годовой	',
            annual: 'Годовой',
        }
    }},
    uz:{
        translation:{
        navigation: {
            main: 'Bosh sahifa',
            cooperation: 'Hamkorlik',
            countries: 'Mamlakatlar',
            internationalOrganizations: 'Xalqaro tashkilotlar',
            internationalNonGovernmentalOrganizations: 'Xalqaro nodavlat tashkilotlar',
            internationalDocuments: 'Xalqaro hujjatlar',
            internationalTreaties: 'Xalqaro shartnomalar',
            experts: 'Mutaxassislar',
            translators: 'Tarjimonlar',
            eventStatistics: 'Statistika',
            visits: 'Tadbirlar',
            events: 'Tashriflar',
            reports: 'Hisobotlar',
            administrations: 'Ma’muriyat',
            employees: 'Hodimlar'
        },
        titles: {
            main: 'Bosh sahifa',
            administration: 'Ma’muriyat',
            cooperation: 'Hamkorlik',
            countries: 'Mamlakatlar',
            eventStatistics: 'Tadbirlar statistikasi',
            experts: 'Mutaxassislar',
            internationalDocuments: 'Xalqaro hujjatlar',
            internationalNonGovernmentalOrganizations: 'Xalqaro nodavlat tashkilotlar',
            internationalOrganizations: 'Xalqaro tashkilotlar',
            internationalsTreaties: 'Xalqaro shartnomalar',
            reports: 'Hisobotlar',
            statistics: 'Statistika',
            statisticsOfCountryVisits: 'Mamlakatlarga tashriflar statistikasi',
            translators: 'Tarjimonlar',
            visitsEmployees: 'Hodimlar tashriflari statistikasi',
            areYouSure: "O'chirishni xohlaysizmi",
            administrator: 'Administrator',
            overallStatistics: 'Umumiy statistika',
            totalMeetings: 'Umumiy uchrashuvlar',
            Agency: 'Agentlik',
            otherOrganizer: 'Boshqa tashkilotchi',
            expertLevel: 'Ekspert darajasidagi',
            organizations: 'Tashkilotlar'
        },
        buttons: {
            back: 'Orqaga',
            today: 'Bugun',
            forward: 'Oldinga',
            month: 'Oy',
            week:'Hafta',
            day: 'Kun',
            excelDownload: 'Excel yuklab olish',
            worldDownload: 'Word yuklab olish',
            print: 'Chop etish',
            create: 'Yaratish',
            edit: 'Tahrirlash',
            delete: "O'chirish",
            retrieve: 'Ko‘rish',
            add: 'Qo‘shish',
            actions: 'Harakatlar',
            cancel: 'Bekor qilish',
            login: 'Kirish',
            logout: 'Chiqish',
            addAnotherFile: 'Yana fayl qo‘shish',
            addAnotherDate: 'Yana sana qo‘shish',
            addAnotherCV: 'Yana bir CV qo‘shish',
            addAnotherCertificate:'Ma’lumotnomani yuklash',
            addAnotherDocument: 'Yana bir hujjat qo‘shish',
            otherCountry: 'Boshqa davlat',
            otherGovernmentBody: 'Boshqa davlat organi',
            addLang: 'Til qo‘shish',
            selectYear: 'Yilni tanlang',
            addReport: 'Hisobot qo‘shish',
            download: 'Yuklab olish',
            active: 'Faol',
            inactive: 'Nofaol',
            sort: {
                sortBy: 'Saralash turi',
                byName: 'Nomi bo‘yicha',
                byVisit: 'Tashrif bo‘yicha',
                byMeeting: 'Uchrashuv bo‘yicha',
                all: 'Barchasi',
                agency: 'Agentlik',
                otherOrganizer: 'Boshqa tashkilotchi',	
            }
        },
        events:{
            conferences: 'Konferensiyalar/Forumlar',
            seminar: 'Seminar/Trening',
            meetings: 'Uchrashuvlar',
            partners: 'Hamkorlar',
            other: 'Boshqa',
            online: 'Onlayn',
            offline: 'Offline',
            letterToMFA: 'TIVga xat',
            MFAResponse: 'TIVdan javob',
            approvalFromMFA: 'TIVdan kelgan kelishuv',
            letterToSSS: 'DXXga xat',
            SSSResponse: 'DXXdan javob',
            approvalFromSSS: 'DXXdan kelgan kelishuv',
            letterToAdministration: 'Administratsiyaga xat',
            administrationResponse: 'Administratsiyadan javob',
            approvalFromAdministration: 'Administratsiyadan kelgan kelishuv',
            foreignVisits: 'Chet el safarlari',
            receptionOfDelegations: 'Delegatsiyalarni qabul qilish',
            diplomaticReceptions: 'Diplomatik qabul marosimlari',

        },
        inputs: {
            selectEvent: 'Tadbirni tanlang',
            enterOrganizer: 'Tashkilotchini kiriting',
            selectFormat: 'Formatni tanlang',
            numberOfParticipants: 'Ishtirokchilar soni',
            selectPartner: 'Hamkorni tanlang',
            selectDonor: 'Donorni tanlang',
            number: 'Raqam',
            selectDate: 'Sanani tanlang',
            title: 'Nomi',
            uploadFile: 'Fayl yuklash',
            placeOfSigning: 'Imzolangan joy',
            enterTitle: 'Nomini kiriting',
            enterFullName: 'F.I.O.ni kiriting',
            additionalInformation: 'Qo‘shimcha ma’lumot',
            uploadCV: 'CV yuklash',
            uploadCertificate: 'Ma’lumotnomani yuklash',
            uploadScannedDocument: 'Hujjat skanerini yuklash',
            governmentBody: 'Davlat organi',
            nameOfGovernmentBody: 'Davlat organi nomi',
            administrationsPermission: 'Ma’muriyat ruxsati',
            contractTitle: 'Shartnoma nomi',
            levelOfSigning: 'Imzolash darajasi',
            mainAreas: 'Asosiy sohalar',
            invitingOrganization: 'Jalb qiluvchi tashkilot',
            selectLanguage: 'Tilni tanlang',
            points: 'Ballar',
            responsible: "Mas'ul",
            name: 'Ism',
            role: 'Rol',
            status: 'Holat',
            lastLogin: 'Oxirgi kirish',
            lastName: 'Familiya',
            phone: 'Telefon raqami',
            email: 'Elektron pochta',
            password: 'Parol',
            nameOfTheOrganization: 'Tashkilot nomi',
            search: 'qidiruv'
        },
        crudNames: {
            event: 'tadbir',
            document: 'hujjat',
            translator: 'tarjimon',
            administrator: 'administrator ',
            expert: 'mutaxassis',
            head: 'rahbar',
            project: 'loyihа',
            agreement: 'shartnoma',
            report: 'hisobot',
            organization: 'tashkilotni',
            employee: 'xodim'
        },
        tableTitles: {
            countries: 'Mamlakat',
            meetings: 'Uchrashuvlar',
            position: 'Lavozim ',
            visits: 'Tashriflar',
            date: 'Sana', 
            name: 'Nomi', 
            place: 'Joy',
            format: 'Format',
            level: 'Daraja',
            period: 'Davr', 
            donor: 'Donor',
            organizer: 'Tashkilotchi',
            additionalInfo: "Qo'shimcha Ma'lumot",
            administrationsConsent: "Ma'muriyatning Roziligi",
            placeOfSigning: "Imzo qo'yish joyi",
            dateOfSigning: "Imzo qo'yish sanasi",
            files: 'Fayllar',
            fullNameOfLeader: 'Rahbarning F.I.Sh.',
            nameOfTheProject: 'Loyiha nomi',
            nameOfMeeting: 'Uchrashuv nomi',
            nameOfDocument: 'Hujjat nomi',
            mainAreas: 'Asosiy sohalar',
            event: 'Tadbir',
            fullName: 'F.I.O.',
            languages: 'Tillar',
            rating: 'Reyting',
            totalNumber: 'Umumiy miqdor',
            organizerAgency: 'Tashkilotchi agentlik',
            otherOrganizer: 'Boshqa tashkilotchi',
            totalEvents: 'Seminar/Trening/Konferensiya/Forum',
            internationalOrganization: 'Xalqaro tashkilot',
            numberOfVisits: 'Tashriflar soni',
            agency: 'Agentlik',
            type: 'Turi',
            responsiblePerson: "Mas'ul shaxs",
            creationDate: 'Yaratilgan sana',
            actions: 'Harakatlar',
            typeOfOrganization: 'Tashkilot turi',
            comment: 'Izoh'
        },
        tablesName: {
            events: 'Tadbirlar',
            visits: 'Tashriflar',
            internationalDocuments: 'Xalqaro hujjatlar',
            leaders : 'Rahbarlar',
            jointProjects: 'Hamkorlik loyihalari',
            meetingTimeline: 'Uchrashuvlar xronologiyasi',
            countryVisitStatistics: 'Mamlakat tashriflari statistikasi',
            staffVisitStatistics: 'Xodimlar tashriflari statistikasi',
            year: 'yil',
            for: 'uchun',
        },
        roles: {
            superAdministrator: 'Super administrator',
            juniorAdministrator: 'Kichik administrator',
            user: 'Foydalanuvchi',
            administrator: 'Administrator'
        },
        typeOfReport:{
            weekly: 'Haftalik',
            monthly: 'Oylik',
            quarterly: 'Choraklik',
            semiAnnual: 'Yarim yillik',
            annual: 'Yillik',
        }
    }}
}